version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - DEV=${DEV}
    volumes:
      - ./frontend:/app
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/nginx/ssl/live/letterflow.maheshalyana.run.place/cert.pem:ro
      - ./privkey.pem:/etc/nginx/ssl/live/letterflow.maheshalyana.run.place/privkey.pem:ro
      - ./chain.pem:/etc/nginx/ssl/live/letterflow.maheshalyana.run.place/chain.pem:ro
      - ./fullchain.pem:/etc/nginx/ssl/live/letterflow.maheshalyana.run.place/fullchain.pem:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - letterflow-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=postgres
      - PORT=3003
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    restart: unless-stopped
    networks:
      - letterflow-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - letterflow-network

networks:
  letterflow-network:
    driver: bridge

volumes:
  postgres-data: 